Repository mhxion/awesome-discord-communities, pull requests merged in 2020-06, with the labels that each got.

#1 Add Svelte
  README.md
  images/server_icons/svelte.png
Labels: new community

#4 Add reddit badge to JetBrains Community
  README.md
Labels: badges

#7 Fix and improve template generation
  src/get_template.py
Labels: enhancement

#8 Fix unnecessary regex #7
  src/get_template.py
Labels: duplicate

#11 Fix Linux Café badges, Add Pi-hole
  README.md
Labels: badges, new community

#12 Order alphabetically
  README.md
Labels: enhancement

#14 Fix awesome-lint errors
  .gitignore
  README.md
Labels: enhancement

#15 Chemistry server updates
  README.md
  images/server_icons/chemistry.png
Labels: badges, not right
